version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBROOTPASS}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASS}
    networks:
      - wp

  wordpress:
    ports:
       - "${PORT:-8000}:80"
    depends_on: 
      - db
    image: wordpress:latest
    volumes: ["./html:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DBUSER}
      WORDPRESS_DB_PASSWORD: ${DBPASS}
      WORDPRESS_DB_NAME: ${DB}
    networks:
      - wp

networks:
  wp:
volumes:
  db_data:


      
    
  